name: integration-tests
run-name: ${{ github.actor }} running integration tests
on: [pull_request]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:

  build:
    runs-on: self-hosted
    name: Checks
    timeout-minutes: 10
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: python test.py
